package com.portosdeveloper.protecworkshopapp.domain.module

data class Package(
    var id: String = "",
    var dateCut: String = "",
    var lote: String = "",
    var name: String = "",
    var gender: String = "",
    var color: String = "",
    var size: String = "",
    var quantity: String = "",
    var ubication: String = "",
    var cutJob: String = "",
    var mergedJob: String = "",
    var cutNecksFistsJob: String = "",
    var necksFistsJob: String = "",
    var mergedFistsNecks: String = "",
    var bodiesJob: String = "",
    var closedJob: String = "",
    var mergedClosed: String = "",
    var terminationJob: String = "",
    var buttonHoleButtonJob: String = "",
    var polishJob: String = "",
    var packingJob: String = "",
    var cutJobPaid: String = "",
    var mergedJobPaid: String = "",
    var cutNecksFistsJobPaid: String = "",
    var necksFistsJobPaid: String = "",
    var bodiesJobPaid: String = "",
    var closedJobPaid: String = "",
    var terminationJobPaid: String = "",
    var buttonHoleButtonJobPaid: String = "",
    var polishJobPaid: String = "",
    var packingJobPaid: String = "",
    var state : String = "Progress"
)
